
// GET ALL QUESTIONS
export const FETCH_REQUESTED = 'questions/FETCH_REQUESTED';
export const FETCH_SUCCEEDED = 'questions/FETCH_SUCCEEDED';
export const FETCH_FAILED = 'questions/FETCH_FAILED';

// CREATE A QUESTION
export const CREATE_QUESTION_REQUESTED = 'question/CREATE_QUESTION_REQUESTED';
export const CREATE_QUESTION_SUCCEEDED = 'question/CREATE_QUESTION_SUCCEEDED';
export const CREATE_QUESTION_FAILED = 'question/CREATE_QUESTION_FAILED';

// GET QUESTION BASED ON ID
export const GET_QUESTION_REQUESTED = 'question/GET_QUESTION_REQUESTED';
export const GET_QUESTION_SUCCEEDED = 'question/GET_QUESTION_SUCCEEDED';
export const GET_QUESTION_FAILED = 'question/GET_QUESTION_FAILED';

// GET ANSWER BASED ON QUESTION ID
export const GET_ANSWERS_REQUESTED = 'answers/GET_ANSWERS_REQUESTED';
export const GET_ANSWERS_SUCCEEDED = 'answers/GET_ANSWERS_SUCCEEDED';
export const GET_ANSWERS_FAILED = 'answers/GET_ANSWERS_FAILED';

// CREATE AN ANSWER
export const CREATE_ANSWER_REQUESTED = 'answer/CREATE_ANSWER_REQUESTED';
export const CREATE_ANSWER_SUCCEEDED = 'answer/CREATE_ANSWER_SUCCEEDED';
export const CREATE_ANSWER_FAILED = 'answer/CREATE_ANSWER_FAILED';